FROM alpine:3.15 AS builder

ADD . /opt/carbon-c-relay-build
WORKDIR /opt/carbon-c-relay-build

RUN \
  apk add --no-cache git bc build-base curl automake autoconf libtool bison flex && \
  ./configure && make

FROM alpine:3.15

RUN mkdir /etc/carbon-c-relay

COPY --from=builder /opt/carbon-c-relay-build/relay /usr/bin/carbon-c-relay
RUN touch cfg
